language: php

sudo: true

dist: trusty

addons:
  firefox: "47.0.1"
  postgresql: "9.5"
  apt:
    packages:
      - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  include:
    - php: 5.6
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_26_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_26_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_27_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_27_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_28_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_28_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_29_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_29_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_30_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_30_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_31_STABLE
        MOODLE_CI_VERSION=1
    - php: 5.6
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_31_STABLE
        MOODLE_CI_VERSION=1
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_32_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_32_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_33_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_33_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_34_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_34_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_35_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_35_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_36_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_36_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_37_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_37_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=pgsql
        MOODLE_BRANCH=MOODLE_38_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.1
      env: 
        DB=mysqli
        MOODLE_BRANCH=MOODLE_38_STABLE
        MOODLE_CI_VERSION=2
    - php: 7.2
      env: 
        DB=pgsql
        MOODLE_BRANCH=master
        MOODLE_CI_VERSION=2
    - php: 7.2
      env: 
        DB=mysqli
        MOODLE_BRANCH=master
        MOODLE_CI_VERSION=2

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - if [[ $MOODLE_CI_VERSION == 1 ]];
    then composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^1;
    else composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2;
    fi
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - if [[ $MOODLE_CI_VERSION == 1 ]];
    then
      if [ -n $GITHUB_APITOKEN ]; then
        cd ci;
        composer config -g github-oauth.github.com $GITHUB_APITOKEN;
        cd ..;
      fi
    fi

  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - if [[ $MOODLE_CI_VERSION == 2 ]];
    then
      moodle-plugin-ci savepoints;
      moodle-plugin-ci mustache;
      moodle-plugin-ci grunt;
    fi
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
